### ISSUE TITLE
patch的类别也就是k=1:K是使用的ref.30的方法吗

### ISSUE THREAD

**Issue by zhangyingbit** [shenwei1231/DeepContour#8]
老师您好，
想问下，最后整幅图的轮廓是如何得到的呢？
另外，随机森林在论文中的作用是什么呢？
谢谢老师

**Comment by shenwei1231** [comment]
Each image patch gives a boundary probability for its center. then the whole boundary in a image is obtained in a sliding-window manner. The boundary probability is predicted by the structured forest.

**Comment by zhangyingbit** [comment]
Thank you for replying! I have got it, and the work is so cool!!!
